### ISSUE TITLE
Attack On Titan Season 3 Part 2

### ISSUE THREAD

**Issue by EnArvy** [MeGaNeKoS/Aniparse#10]
Actual:
```
{
 'file_name': 'Attack On Titan Season 3 Part 2',
 'anime_title': 'Attack On Titan',
 'anime_season_prefix': 'Season',
 'anime_season': 3,
 'episode_title': 'Part 2'
}
```
Proposed Solution:

Ignore season detection, let `'anime_title':'Attack On Titan Season 3 Part 2`.
Maybe add option to toggle season detection. 

Reason:

Western sites such as TVDB and TMDB use seasons for shows and group all seasons of a show. However sites such as Anilist and Myanimelist consider each season to be a different independent entry.

**Comment by MeGaNeKoS** [comment]
This happen because there is no episode number.  However, it is quite weird for seasoned anime to have episode title. Therefore, my purpose is in `validate_element` we check if there'se episode title, but no episode number, and if the anime_type not `[movie, gekijouban]` . Than we concate everything from episode title to anime title.
Reason:
I dont think having togle option is a good **IDEA**, as this library mean to be an automatic. If we add that, that could break parser for another title.

**Comment by EnArvy** [comment]
I will let you decide the exact implementation for this specific issue. However, many programs use Anilist and MAL for scraping data, and I believe something like `options={'seasons_as_unique_entries':true}` would be a good feature to implement, and when this will be true, aniparse will not detect season but only episode and combine season with title.

**Comment by MeGaNeKoS** [comment]
After looking of other anime title, This changes only help a certain title, but could break other title. For example, `To Love ru season 2` is `motto to love ru`. `Zero no Tsukaima` is ` Zero no Tsukaima: Futatsuki no Kishi`. As you can see here, there's no indication about their season. Therefore, `seasons_as_unique_entries` will not implemented. But, `season_part_as_unique` will be implement. 

`season_part_as_unique` behavior are if set true, then `Attack On Titan Season 3 Part 2` will be detected as a single title. Otherwise, it will return as current output. This behavior will consist whether there's an episode number or not.

Example: `season_part_as_unique: True`
```
{
 'file_name': 'Attack On Titan Season 3 Part 2',
 'anime_title': 'Attack On Titan Season 3 Part 2',
},
{
 'file_name': 'Attack On Titan Season 3 Part 2' - 01,
 'anime_title': 'Attack On Titan Season 3 Part 2',
 'episode_number': 1
}
```
Example: `season_part_as_unique: False`
```
{
 'file_name': 'Attack On Titan Season 3 Part 2',
 'anime_title': 'Attack On Titan',
 'anime_season_prefix': 'Season',
 'anime_season': 3,
 'episode_title': 'Part 2'
},
{
 'file_name': 'Attack On Titan Season 3 Part 2' - 01,
 'anime_title': 'Attack On Titan',
 'anime_season_prefix': 'Season',
 'anime_season': 3,
 'episode_number': 1
}
```

**Comment by EnArvy** [comment]
This is exactly what I wanted, thanks!

**Comment by MeGaNeKoS** [comment]
New update has been [released](https://pypi.org/project/aniparse/).
